#ifndef PDC_MESSAGE_H_
#define PDC_MESSAGE_H_

#include <stdint.h>

#include "common.h"
#include "pimu_device_connector.h"

#define PDC_MESSAGE_DESTINATION_NONE 0x00

#define PDC_MESSAGE_DESTINATION_DEVICE_HANDSHAKE 0x01
#define PDC_MESSAGE_DESTINATION_DEVICE_DISCONNECT 0x02
#define PDC_MESSAGE_DESTINATION_DEVICE_FIRMWARE 0x03
#define PDC_MESSAGE_DESTINATION_DEVICE_GAMEPAD 0x04
#define PDC_MESSAGE_DESTINATION_DEVICE_INPUT 0x05

#define PDC_MESSAGE_DESTINATION_DESKTOP_HANDSHAKE 0x81
#define PDC_MESSAGE_DESTINATION_DESKTOP_DEBUG 0x82
#define PDC_MESSAGE_DESTINATION_DESKTOP_FIRMWARE 0x83
#define PDC_MESSAGE_DESTINATION_DESKTOP_GAMEPAD 0x84


#define PDC_MESSAGE_DEVICE_FIRMWARE_DATA_TYPE_NONE 0x00
#define PDC_MESSAGE_DEVICE_FIRMWARE_DATA_TYPE_REQUEST_CONFIG 0x01
#define PDC_MESSAGE_DEVICE_FIRMWARE_DATA_TYPE_SET_CONFIG 0x02

#define PDC_MESSAGE_DEVICE_GAMEPAD_DATA_TYPE_NONE 0x00
#define PDC_MESSAGE_DEVICE_GAMEPAD_DATA_TYPE_REQUEST_COLORS 0x01
#define PDC_MESSAGE_DEVICE_GAMEPAD_DATA_TYPE_SET_COLORS 0x02
#define PDC_MESSAGE_DEVICE_GAMEPAD_DATA_TYPE_REQUEST_PLAYER_LEDS 0x03

#define PDC_MESSAGE_DESKTOP_FIRMWARE_DATA_TYPE_NONE 0x00
#define PDC_MESSAGE_DESKTOP_FIRMWARE_DATA_TYPE_CURRENT_CONFIG 0x01

#define PDC_MESSAGE_DESKTOP_DEBUG_DATA_TYPE_NONE 0x00
#define PDC_MESSAGE_DESKTOP_DEBUG_DATA_TYPE_STRING 0x01
#define PDC_MESSAGE_DESKTOP_DEBUG_DATA_TYPE_DATA 0x02

#define PDC_MESSAGE_DESKTOP_GAMEPAD_DATA_TYPE_NONE 0x00
#define PDC_MESSAGE_DESKTOP_GAMEPAD_DATA_TYPE_CURRENT_COLORS 0x01
#define PDC_MESSAGE_DESKTOP_GAMEPAD_DATA_TYPE_PLAYER_LEDS 0x02


#define PDC_MESSAGE_CHAR_TERMINATION 0
#define PDC_MESSAGE_CHAR_ESCAPE 0xFF

typedef PACKED_STRUCT
{
    uint8_t destination;
    uint8_t data_type;
    uint16_t data_size;
}
PDCMessageHeader;

typedef PACKED_STRUCT
{
    PDCMessageHeader header;
    uint8_t data[PDC_MESSAGE_DATA_MAX_SIZE];
}
PDCMessage;

typedef PACKED_STRUCT
{
    uint32_t crc;
}
PDCMessageCrcHeader;

typedef PACKED_STRUCT
{
    PDCMessageCrcHeader header;
    PDCMessage message;
}
PDCMessageCrc;

typedef struct
{
    uint8_t buffer[sizeof(PDCMessageCrc) * 2 + 3];
    uint16_t size;
} PDCEscapedMessageCrc;

uint16_t pdc_message_get_size(PDCMessage *message);
uint16_t pdc_escape_message(PDCMessage *message, PDCEscapedMessageCrc* destination);

#endif